"""
=============================================================================
MODULE 1: DEVICE SYSTEM REPORT SIMULATOR
=============================================================================

PURPOSE:
    Simulates the raw system report that an Apple device would generate.
    In production, this data comes from iOS/macOS system APIs.
    For our prototype, we generate realistic device snapshots.

WHAT THIS GIVES US:
    - Battery health, cycle count, temperature history
    - Storage breakdown by category
    - Connectivity status (Wi-Fi, Bluetooth, Cellular)
    - Sensor readings (accelerometer, gyroscope, proximity, ambient light)
    - Display health metrics
    - Crash logs and thermal events
    - Camera subsystem status

WHY IT MATTERS FOR THE DIAGNOSTICS PASSPORT:
    This is the "ground truth" data layer. Combined with the customer's
    self-reported symptoms, we triangulate to root cause. Generic triage
    asks "what's wrong?" — our system ALSO asks the device "what do your
    logs say?" and cross-references the two.

=============================================================================
"""

import random
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Data Structures: What a Device Report Looks Like
# ---------------------------------------------------------------------------

@dataclass
class BatteryReport:
    """What the device's battery subsystem reports."""
    health_percentage: float        # 100% = new, <80% = service recommended
    cycle_count: int                # Number of full charge cycles
    max_capacity_mah: int           # Current max capacity in milliamp-hours
    design_capacity_mah: int        # Original design capacity
    temperature_celsius: float      # Current battery temperature
    peak_temps_last_30_days: list   # List of peak temps (thermal stress indicator)
    charging_pattern: str           # "regular", "overnight_prolonged", "fast_charge_heavy"
    unexpected_shutdowns: int       # Count in last 30 days


@dataclass
class StorageReport:
    """What the device's storage subsystem reports."""
    total_gb: float
    used_gb: float
    system_gb: float
    apps_gb: float
    photos_gb: float
    other_gb: float                 # "Other" is often the mystery bloat category
    available_gb: float


@dataclass
class ConnectivityReport:
    """Wi-Fi, Bluetooth, and Cellular subsystem status."""
    wifi_connected: bool
    wifi_signal_strength_dbm: int   # -30 = excellent, -90 = very poor
    wifi_drops_last_7_days: int
    bluetooth_connected: bool
    bluetooth_devices_paired: int
    bluetooth_drops_last_7_days: int
    cellular_signal_bars: int       # 0-4
    cellular_drops_last_7_days: int
    airplane_mode_toggles: int      # Frequent toggling = user troubleshooting


@dataclass
class DisplayReport:
    """Display subsystem health metrics."""
    brightness_responsive: bool
    true_tone_functional: bool
    touch_response_ms: float        # Average touch latency (normal: 5-15ms)
    dead_pixels_detected: int
    refresh_rate_anomalies: int     # Count of rate drops in last 7 days
    flicker_events_logged: int      # Intermittent flicker detections


@dataclass
class SensorReport:
    """Hardware sensor subsystem readings."""
    accelerometer_functional: bool
    gyroscope_functional: bool
    proximity_sensor_functional: bool
    ambient_light_sensor_functional: bool
    face_id_functional: Optional[bool]
    lidar_functional: Optional[bool]


@dataclass
class CameraReport:
    """Camera subsystem status."""
    rear_camera_functional: bool
    front_camera_functional: bool
    autofocus_responsive: bool
    image_stabilization_functional: bool
    lens_obstruction_detected: bool  # Debris, smudge, crack over lens
    flash_functional: bool


@dataclass
class CrashLog:
    """A single crash event from the device logs."""
    timestamp: str
    process_name: str               # Which app/service crashed
    crash_type: str                 # "kernel_panic", "app_crash", "watchdog_timeout"
    related_hardware: Optional[str] # If crash implicates hardware (e.g., "GPU", "baseband")


@dataclass
class DeviceSystemReport:
    """
    THE COMPLETE DEVICE SYSTEM REPORT

    This is everything the device knows about itself.
    In production: pulled from iOS/macOS diagnostic APIs.
    In our prototype: generated by the simulator below.
    """
    # Device identity
    device_model: str
    serial_number: str
    os_version: str
    applecare_status: str           # "active", "expired", "none"
    device_age_months: int

    # Subsystem reports
    battery: BatteryReport
    storage: StorageReport
    connectivity: ConnectivityReport
    display: DisplayReport
    sensors: SensorReport
    camera: CameraReport

    # Event logs
    crash_logs: list                 # List of CrashLog objects
    thermal_events_last_30_days: int
    last_restart: str
    uptime_hours: float


# ---------------------------------------------------------------------------
# The Simulator: Generates Realistic Device Reports
# ---------------------------------------------------------------------------

class DeviceReportSimulator:
    """
    Generates realistic device system reports for prototype testing.

    USAGE:
        simulator = DeviceReportSimulator()

        # Healthy device
        report = simulator.generate(profile="healthy")

        # Device with battery issues
        report = simulator.generate(profile="battery_degraded")

        # Device with intermittent display problems
        report = simulator.generate(profile="display_intermittent")

        # Device with multiple compounding issues
        report = simulator.generate(profile="multi_failure")
    """

    DEVICE_MODELS = [
        "iPhone 15 Pro Max", "iPhone 15 Pro", "iPhone 15",
        "iPhone 14 Pro Max", "iPhone 14 Pro", "iPhone 14",
        "iPhone 13 Pro", "iPhone 13", "iPhone SE (3rd gen)",
    ]

    # Each profile simulates a realistic failure scenario
    # based on actual patterns from our user research
    PROFILES = {
        "healthy":              "Device in good condition — baseline for comparison",
        "battery_degraded":     "Battery below 80% health, high cycle count, unexpected shutdowns",
        "storage_full":         "Storage nearly full causing performance issues",
        "connectivity_issues":  "Frequent Wi-Fi/Bluetooth drops",
        "display_intermittent": "Intermittent flicker/touch issues (the repeat-visit driver)",
        "camera_malfunction":   "Camera hardware issues — lens obstruction or autofocus failure",
        "software_unstable":    "Frequent crashes, thermal events, needs OS-level intervention",
        "multi_failure":        "Multiple compounding issues — complex triage case",
    }

    def generate(self, profile: str = "healthy",
                 device_model: str = None) -> DeviceSystemReport:
        """
        Generate a complete device system report for a given failure profile.

        Args:
            profile: One of the keys in PROFILES above
            device_model: Specific model, or random if None

        Returns:
            DeviceSystemReport with all subsystem data populated
        """
        model = device_model or random.choice(self.DEVICE_MODELS)
        serial = f"F2L{random.randint(1000000, 9999999)}XYZ"

        # Route to the appropriate scenario generator
        generators = {
            "healthy":              self._healthy,
            "battery_degraded":     self._battery_degraded,
            "storage_full":         self._storage_full,
            "connectivity_issues":  self._connectivity_issues,
            "display_intermittent": self._display_intermittent,
            "camera_malfunction":   self._camera_malfunction,
            "software_unstable":    self._software_unstable,
            "multi_failure":        self._multi_failure,
        }

        generator = generators.get(profile, self._healthy)
        return generator(model, serial)

    # --- Scenario Generators ---

    def _healthy(self, model, serial):
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 18.3.1", applecare_status="active",
            device_age_months=8,
            battery=BatteryReport(
                health_percentage=96.0, cycle_count=187,
                max_capacity_mah=4323, design_capacity_mah=4441,
                temperature_celsius=28.5,
                peak_temps_last_30_days=[31.2, 29.8, 30.1],
                charging_pattern="regular",
                unexpected_shutdowns=0
            ),
            storage=StorageReport(
                total_gb=256, used_gb=142, system_gb=15,
                apps_gb=48, photos_gb=62, other_gb=17, available_gb=114
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-42,
                wifi_drops_last_7_days=0,
                bluetooth_connected=True, bluetooth_devices_paired=4,
                bluetooth_drops_last_7_days=0,
                cellular_signal_bars=4, cellular_drops_last_7_days=0,
                airplane_mode_toggles=1
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=8.2, dead_pixels_detected=0,
                refresh_rate_anomalies=0, flicker_events_logged=0
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=True
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[],
            thermal_events_last_30_days=0,
            last_restart=(datetime.now() - timedelta(days=3)).isoformat(),
            uptime_hours=72.5
        )

    def _battery_degraded(self, model, serial):
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 18.2", applecare_status="active",
            device_age_months=26,
            battery=BatteryReport(
                health_percentage=74.0, cycle_count=847,
                max_capacity_mah=3287, design_capacity_mah=4441,
                temperature_celsius=34.2,
                peak_temps_last_30_days=[38.5, 41.2, 39.8, 37.1, 40.5],
                charging_pattern="overnight_prolonged",
                unexpected_shutdowns=7
            ),
            storage=StorageReport(
                total_gb=128, used_gb=98, system_gb=12,
                apps_gb=35, photos_gb=38, other_gb=13, available_gb=30
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-55,
                wifi_drops_last_7_days=2,
                bluetooth_connected=True, bluetooth_devices_paired=3,
                bluetooth_drops_last_7_days=1,
                cellular_signal_bars=3, cellular_drops_last_7_days=1,
                airplane_mode_toggles=5
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=9.1, dead_pixels_detected=0,
                refresh_rate_anomalies=0, flicker_events_logged=0
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=None
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=2)).isoformat(),
                    process_name="SpringBoard",
                    crash_type="watchdog_timeout",
                    related_hardware="battery_controller"
                ),
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=5)).isoformat(),
                    process_name="thermalmonitord",
                    crash_type="kernel_panic",
                    related_hardware="battery_thermal"
                ),
            ],
            thermal_events_last_30_days=12,
            last_restart=(datetime.now() - timedelta(hours=6)).isoformat(),
            uptime_hours=6.2
        )

    def _storage_full(self, model, serial):
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 17.6", applecare_status="expired",
            device_age_months=30,
            battery=BatteryReport(
                health_percentage=88.0, cycle_count=512,
                max_capacity_mah=3908, design_capacity_mah=4441,
                temperature_celsius=30.1,
                peak_temps_last_30_days=[32.0, 31.5],
                charging_pattern="regular",
                unexpected_shutdowns=0
            ),
            storage=StorageReport(
                total_gb=64, used_gb=61.8, system_gb=10,
                apps_gb=22, photos_gb=18, other_gb=11.8, available_gb=2.2
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-48,
                wifi_drops_last_7_days=0,
                bluetooth_connected=False, bluetooth_devices_paired=2,
                bluetooth_drops_last_7_days=0,
                cellular_signal_bars=4, cellular_drops_last_7_days=0,
                airplane_mode_toggles=0
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=11.5, dead_pixels_detected=0,
                refresh_rate_anomalies=2, flicker_events_logged=0
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=None
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=1)).isoformat(),
                    process_name="Camera",
                    crash_type="app_crash",
                    related_hardware=None
                ),
            ],
            thermal_events_last_30_days=1,
            last_restart=(datetime.now() - timedelta(days=14)).isoformat(),
            uptime_hours=336.0
        )

    def _connectivity_issues(self, model, serial):
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 18.3", applecare_status="active",
            device_age_months=14,
            battery=BatteryReport(
                health_percentage=92.0, cycle_count=340,
                max_capacity_mah=4086, design_capacity_mah=4441,
                temperature_celsius=29.0,
                peak_temps_last_30_days=[30.5, 31.0],
                charging_pattern="regular",
                unexpected_shutdowns=0
            ),
            storage=StorageReport(
                total_gb=256, used_gb=165, system_gb=14,
                apps_gb=55, photos_gb=72, other_gb=24, available_gb=91
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-72,
                wifi_drops_last_7_days=18,
                bluetooth_connected=False, bluetooth_devices_paired=6,
                bluetooth_drops_last_7_days=12,
                cellular_signal_bars=2, cellular_drops_last_7_days=8,
                airplane_mode_toggles=23   # User is desperately toggling
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=8.8, dead_pixels_detected=0,
                refresh_rate_anomalies=0, flicker_events_logged=0
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=True
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=1)).isoformat(),
                    process_name="wifid",
                    crash_type="app_crash",
                    related_hardware="wifi_module"
                ),
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=3)).isoformat(),
                    process_name="bluetoothd",
                    crash_type="watchdog_timeout",
                    related_hardware="bluetooth_module"
                ),
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=4)).isoformat(),
                    process_name="CommCenter",
                    crash_type="app_crash",
                    related_hardware="baseband"
                ),
            ],
            thermal_events_last_30_days=2,
            last_restart=(datetime.now() - timedelta(hours=2)).isoformat(),
            uptime_hours=2.1
        )

    def _display_intermittent(self, model, serial):
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 18.3.1", applecare_status="active",
            device_age_months=11,
            battery=BatteryReport(
                health_percentage=94.0, cycle_count=245,
                max_capacity_mah=4174, design_capacity_mah=4441,
                temperature_celsius=29.5,
                peak_temps_last_30_days=[31.0, 30.5],
                charging_pattern="regular",
                unexpected_shutdowns=1
            ),
            storage=StorageReport(
                total_gb=256, used_gb=118, system_gb=14,
                apps_gb=42, photos_gb=48, other_gb=14, available_gb=138
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-45,
                wifi_drops_last_7_days=0,
                bluetooth_connected=True, bluetooth_devices_paired=5,
                bluetooth_drops_last_7_days=0,
                cellular_signal_bars=4, cellular_drops_last_7_days=0,
                airplane_mode_toggles=0
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=18.5,     # Elevated — should be 5-15ms
                dead_pixels_detected=0,
                refresh_rate_anomalies=14,  # Significant
                flicker_events_logged=8     # The intermittent issue
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=True
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=1)).isoformat(),
                    process_name="backboardd",
                    crash_type="watchdog_timeout",
                    related_hardware="display_controller"
                ),
            ],
            thermal_events_last_30_days=1,
            last_restart=(datetime.now() - timedelta(days=5)).isoformat(),
            uptime_hours=120.0
        )

    def _camera_malfunction(self, model, serial):
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 18.3.1", applecare_status="active",
            device_age_months=6,
            battery=BatteryReport(
                health_percentage=98.0, cycle_count=120,
                max_capacity_mah=4352, design_capacity_mah=4441,
                temperature_celsius=27.5,
                peak_temps_last_30_days=[29.0, 28.5],
                charging_pattern="regular",
                unexpected_shutdowns=0
            ),
            storage=StorageReport(
                total_gb=512, used_gb=195, system_gb=16,
                apps_gb=68, photos_gb=85, other_gb=26, available_gb=317
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-38,
                wifi_drops_last_7_days=0,
                bluetooth_connected=True, bluetooth_devices_paired=3,
                bluetooth_drops_last_7_days=0,
                cellular_signal_bars=4, cellular_drops_last_7_days=0,
                airplane_mode_toggles=0
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=7.5, dead_pixels_detected=0,
                refresh_rate_anomalies=0, flicker_events_logged=0
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=True
            ),
            camera=CameraReport(
                rear_camera_functional=False,   # Main camera failing
                front_camera_functional=True,
                autofocus_responsive=False,      # Autofocus broken
                image_stabilization_functional=False,  # OIS failing
                lens_obstruction_detected=True,  # Debris detected
                flash_functional=True
            ),
            crash_logs=[
                CrashLog(
                    timestamp=(datetime.now() - timedelta(hours=3)).isoformat(),
                    process_name="Camera",
                    crash_type="app_crash",
                    related_hardware="rear_camera_module"
                ),
                CrashLog(
                    timestamp=(datetime.now() - timedelta(days=1)).isoformat(),
                    process_name="mediaserverd",
                    crash_type="app_crash",
                    related_hardware="rear_camera_module"
                ),
            ],
            thermal_events_last_30_days=0,
            last_restart=(datetime.now() - timedelta(days=7)).isoformat(),
            uptime_hours=168.0
        )

    def _software_unstable(self, model, serial):
        now = datetime.now()
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 17.4",  # Outdated OS
            applecare_status="active",
            device_age_months=18,
            battery=BatteryReport(
                health_percentage=89.0, cycle_count=445,
                max_capacity_mah=3953, design_capacity_mah=4441,
                temperature_celsius=36.8,  # Running hot
                peak_temps_last_30_days=[42.1, 40.5, 39.8, 41.3, 38.9, 40.2],
                charging_pattern="fast_charge_heavy",
                unexpected_shutdowns=3
            ),
            storage=StorageReport(
                total_gb=128, used_gb=115, system_gb=18,  # Bloated system
                apps_gb=42, photos_gb=35, other_gb=20, available_gb=13
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-52,
                wifi_drops_last_7_days=4,
                bluetooth_connected=True, bluetooth_devices_paired=5,
                bluetooth_drops_last_7_days=2,
                cellular_signal_bars=3, cellular_drops_last_7_days=3,
                airplane_mode_toggles=8
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=True,
                touch_response_ms=14.2, dead_pixels_detected=0,
                refresh_rate_anomalies=5, flicker_events_logged=0
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=True,
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=None
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[
                CrashLog(timestamp=(now - timedelta(hours=2)).isoformat(),
                         process_name="SpringBoard", crash_type="app_crash",
                         related_hardware=None),
                CrashLog(timestamp=(now - timedelta(hours=8)).isoformat(),
                         process_name="kernel_task", crash_type="kernel_panic",
                         related_hardware=None),
                CrashLog(timestamp=(now - timedelta(days=1)).isoformat(),
                         process_name="Safari", crash_type="app_crash",
                         related_hardware=None),
                CrashLog(timestamp=(now - timedelta(days=1, hours=5)).isoformat(),
                         process_name="Mail", crash_type="app_crash",
                         related_hardware=None),
                CrashLog(timestamp=(now - timedelta(days=2)).isoformat(),
                         process_name="thermalmonitord", crash_type="watchdog_timeout",
                         related_hardware=None),
            ],
            thermal_events_last_30_days=18,
            last_restart=(now - timedelta(hours=2)).isoformat(),
            uptime_hours=2.0
        )

    def _multi_failure(self, model, serial):
        """The complex case: battery + display + connectivity compounding."""
        now = datetime.now()
        return DeviceSystemReport(
            device_model=model, serial_number=serial,
            os_version="iOS 18.1", applecare_status="active",
            device_age_months=22,
            battery=BatteryReport(
                health_percentage=71.0, cycle_count=923,
                max_capacity_mah=3153, design_capacity_mah=4441,
                temperature_celsius=37.5,
                peak_temps_last_30_days=[43.2, 41.8, 40.5, 42.1, 39.9],
                charging_pattern="overnight_prolonged",
                unexpected_shutdowns=11
            ),
            storage=StorageReport(
                total_gb=128, used_gb=108, system_gb=16,
                apps_gb=38, photos_gb=35, other_gb=19, available_gb=20
            ),
            connectivity=ConnectivityReport(
                wifi_connected=True, wifi_signal_strength_dbm=-68,
                wifi_drops_last_7_days=9,
                bluetooth_connected=False, bluetooth_devices_paired=4,
                bluetooth_drops_last_7_days=7,
                cellular_signal_bars=2, cellular_drops_last_7_days=5,
                airplane_mode_toggles=15
            ),
            display=DisplayReport(
                brightness_responsive=True, true_tone_functional=False,
                touch_response_ms=22.3,
                dead_pixels_detected=3,
                refresh_rate_anomalies=21,
                flicker_events_logged=15
            ),
            sensors=SensorReport(
                accelerometer_functional=True, gyroscope_functional=True,
                proximity_sensor_functional=False,  # Failed
                ambient_light_sensor_functional=True,
                face_id_functional=True, lidar_functional=None
            ),
            camera=CameraReport(
                rear_camera_functional=True, front_camera_functional=True,
                autofocus_responsive=True,
                image_stabilization_functional=True,
                lens_obstruction_detected=False, flash_functional=True
            ),
            crash_logs=[
                CrashLog(timestamp=(now - timedelta(hours=1)).isoformat(),
                         process_name="backboardd", crash_type="watchdog_timeout",
                         related_hardware="display_controller"),
                CrashLog(timestamp=(now - timedelta(hours=4)).isoformat(),
                         process_name="SpringBoard", crash_type="app_crash",
                         related_hardware="battery_controller"),
                CrashLog(timestamp=(now - timedelta(days=1)).isoformat(),
                         process_name="wifid", crash_type="app_crash",
                         related_hardware="wifi_module"),
                CrashLog(timestamp=(now - timedelta(days=2)).isoformat(),
                         process_name="thermalmonitord", crash_type="kernel_panic",
                         related_hardware="battery_thermal"),
            ],
            thermal_events_last_30_days=22,
            last_restart=(now - timedelta(hours=1)).isoformat(),
            uptime_hours=1.2
        )


# ---------------------------------------------------------------------------
# Quick Test: See what a report looks like
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sim = DeviceReportSimulator()

    print("=" * 60)
    print("AVAILABLE DEVICE PROFILES:")
    print("=" * 60)
    for name, desc in sim.PROFILES.items():
        print(f"  {name:25s} → {desc}")

    print("\n" + "=" * 60)
    print("SAMPLE REPORT: battery_degraded")
    print("=" * 60)

    report = sim.generate("battery_degraded")
    print(f"  Device:     {report.device_model}")
    print(f"  Serial:     {report.serial_number}")
    print(f"  OS:         {report.os_version}")
    print(f"  AppleCare:  {report.applecare_status}")
    print(f"  Age:        {report.device_age_months} months")
    print(f"  Battery:    {report.battery.health_percentage}% "
          f"({report.battery.cycle_count} cycles)")
    print(f"  Shutdowns:  {report.battery.unexpected_shutdowns} in 30 days")
    print(f"  Thermals:   {report.thermal_events_last_30_days} events")
    print(f"  Crashes:    {len(report.crash_logs)} logged")
